#ifndef RADAR_CONFIG_H
#define RADAR_CONFIG_H

#if defined(__has_include)
#if __has_include("sdkconfig.h")
#include "sdkconfig.h"
#define RADAR_CONFIG_HAS_SDKCONFIG 1
#endif
#endif

#ifndef CONFIG_S3_RADAR_PER_SOURCE_LOG_SCHEDULER
#define CONFIG_S3_RADAR_PER_SOURCE_LOG_SCHEDULER 1
#endif

#ifndef CONFIG_S3_RADAR_ZONE_ACTIVE
#define CONFIG_S3_RADAR_ZONE_ACTIVE 1
#endif

/*
 * S3 本地 HLK-LD2450 雷达的集中配置入口。
 *
 * 修改接线、采样节奏、恢复策略或空间判定参数时，优先只改本文件。
 * 当前默认值对应已确认的接线：UART1、TX=GPIO18、RX=GPIO17、256000 baud、8N1。
 * 坐标默认保持 LD2450 原始坐标轴，未经真机确认不要翻转或旋转。
 */

/* --------------------------- 板级 UART / GPIO --------------------------- */

/* UART 端口和 GPIO 优先由 sdkconfig.defaults/Kconfig 提供，便于按板卡覆盖。 */
#ifdef RADAR_CONFIG_HAS_SDKCONFIG
#define RADAR_CONFIG_UART_PORT_INDEX CONFIG_S3_LOCAL_LD2450_UART_PORT
#define RADAR_CONFIG_UART_TX_GPIO CONFIG_S3_LOCAL_LD2450_UART_TX_GPIO
#define RADAR_CONFIG_UART_RX_GPIO CONFIG_S3_LOCAL_LD2450_UART_RX_GPIO

#ifdef CONFIG_S3_LOCAL_LD2450_UART_ENABLED
#define RADAR_CONFIG_UART_REQUESTED 1
#else
#define RADAR_CONFIG_UART_REQUESTED 0
#endif
#else
/* 主机离线测试不生成 sdkconfig.h，使用与 sdkconfig.defaults 相同的默认接线。 */
#define RADAR_CONFIG_UART_PORT_INDEX 1
#define RADAR_CONFIG_UART_TX_GPIO 18
#define RADAR_CONFIG_UART_RX_GPIO 17
#define RADAR_CONFIG_UART_REQUESTED 1
#endif

#define RADAR_CONFIG_UART_ENABLED \
    (RADAR_CONFIG_UART_REQUESTED && \
     RADAR_CONFIG_UART_PORT_INDEX >= 0 && \
     RADAR_CONFIG_UART_TX_GPIO >= 0 && \
     RADAR_CONFIG_UART_RX_GPIO >= 0)

#define RADAR_CONFIG_LOCAL_ID 0
#define RADAR_CONFIG_BOARD_NAME "S3_LOCAL"
#define RADAR_CONFIG_UART_BAUD_RATE 256000
#define RADAR_CONFIG_UART_RX_RING_BYTES 1024
#define RADAR_CONFIG_UART_READ_BYTES 128
#define RADAR_CONFIG_UART_READ_TIMEOUT_MS 100
#define RADAR_CONFIG_UART_IDLE_DELAY_MS 20
#define RADAR_CONFIG_UART_RECOVERY_DELAY_CAP_MS 100
#define RADAR_CONFIG_UART_DIAGNOSTICS_LOG_MS 1000
#ifndef RADAR_UART_RAW_DEBUG
#define RADAR_UART_RAW_DEBUG 0
#endif
#define RADAR_CONFIG_UART_RX_TASK_STACK 4096
#define RADAR_CONFIG_UART_RX_TASK_PRIORITY 5

/* Every PSRAM-backed radar allocation admits against both aggregate free
 * capacity and the largest contiguous block.  Keep a small fixed margin for
 * allocator metadata and the next bounded workspace instead of accepting an
 * allocation that leaves the module unable to recover. */
#define RADAR_CONFIG_PSRAM_ALLOCATION_HEADROOM_BYTES 4096U
#define RADAR_CONFIG_TASK_STOP_TIMEOUT_MS 500U
/* UART driver owns an internal RX ring/event queue.  Reject a new driver
 * instance when fragmentation cannot leave a safe bounded control margin. */
#define RADAR_CONFIG_UART_INTERNAL_MIN_FREE_BYTES 12288U
#define RADAR_CONFIG_UART_INTERNAL_MIN_LARGEST_BYTES 4096U

/* --------------------------- UART 恢复策略 --------------------------- */

/* 连续达到错误次数后停止读取并进入退避重连。 */
#define RADAR_CONFIG_UART_ERROR_THRESHOLD 3U
/* 连续完全没有 RX 字节达到该时长后认为链路静默并进入退避重连。 */
#define RADAR_CONFIG_UART_SILENT_TIMEOUT_MS 3000U
/* 第一次重试等待时间，以及指数退避上限。 */
#define RADAR_CONFIG_UART_BACKOFF_INITIAL_MS 250U
#define RADAR_CONFIG_UART_BACKOFF_MAX_MS 8000U
/* 重连后需要连续收到的有效帧数，达到后才恢复 VALID。 */
#define RADAR_CONFIG_UART_VALID_FRAMES_REQUIRED 3U

/* --------------------------- 传统存在状态 --------------------------- */

#define RADAR_CONFIG_FRAME_PERIOD_EXPECTED_MS 100U
#define RADAR_CONFIG_ONLINE_TIMEOUT_MS 3000U
#define RADAR_CONFIG_ENTER_WINDOW_FRAMES 3U
#define RADAR_CONFIG_ENTER_REQUIRED_FRAMES 2U
#define RADAR_CONFIG_SHORT_GAP_MS 1000U
#define RADAR_CONFIG_HOLD_TIMEOUT_MS 900000U
#define RADAR_CONFIG_REPORT_HEARTBEAT_MS 1000U
#define RADAR_CONFIG_TARGET_REPORT_MIN_INTERVAL_MS 500U

/* --------------------------- 空间状态 / 坐标 --------------------------- */

#define RADAR_CONFIG_FLIP_X 0
#define RADAR_CONFIG_FLIP_Y 0
#define RADAR_CONFIG_ROTATION_DEG 0
#define RADAR_CONFIG_ORIGIN_OFFSET_X_MM 0
#define RADAR_CONFIG_ORIGIN_OFFSET_Y_MM 0
#define RADAR_CONFIG_MAX_DETECTION_DISTANCE_MM 6000U

#define RADAR_CONFIG_ROOM_MIN_X_MM (-6000)
#define RADAR_CONFIG_ROOM_MAX_X_MM 6000
#define RADAR_CONFIG_ROOM_MIN_Y_MM (-6000)
#define RADAR_CONFIG_ROOM_MAX_Y_MM 6000

/* 当前只启用一个覆盖整个房间的 active 区域；后续可在此扩展固定区域。 */
#define RADAR_CONFIG_ZONE_COUNT 1U
#define RADAR_CONFIG_ZONE_0_ID 1U
#define RADAR_CONFIG_ZONE_0_TYPE 1U /* RADAR_ZONE_ACTIVE */
#define RADAR_CONFIG_ZONE_0_ENABLED 1
#define RADAR_CONFIG_ZONE_0_MIN_X_MM (-6000)
#define RADAR_CONFIG_ZONE_0_MAX_X_MM 6000
#define RADAR_CONFIG_ZONE_0_MIN_Y_MM (-6000)
#define RADAR_CONFIG_ZONE_0_MAX_Y_MM 6000
#define RADAR_CONFIG_ZONE_0_HYSTERESIS_MM 250U

/* 空间状态机阈值，单位按宏名后缀：mm、cm/s 或 ms。 */
#define RADAR_CONFIG_SENSOR_STALE_MS 3000U
#define RADAR_CONFIG_ASSOCIATION_GATE_MM 900U
#define RADAR_CONFIG_ASSOCIATION_GATE_MIN_MM 800U
#define RADAR_CONFIG_ASSOCIATION_GATE_MAX_MM 1200U
#define RADAR_CONFIG_TRACK_TIMEOUT_MS 1800U
#define RADAR_CONFIG_TRACK_CONFIRM_FRAMES 2U
#define RADAR_CONFIG_TRACK_HOLD_MS 500U
#define RADAR_CONFIG_MOTION_SPEED_CM_S 15U
#define RADAR_CONFIG_MOTION_DISPLACEMENT_MM 120U
#define RADAR_CONFIG_STILL_CANDIDATE_FRAMES 3U
#define RADAR_CONFIG_HOLD_DECAY_MS 1500U
#define RADAR_CONFIG_HOLD_CONFIDENCE_LOSS_PER_S 20U
#define RADAR_CONFIG_CONFIDENCE_INITIAL 40U
#define RADAR_CONFIG_CONFIDENCE_GAIN_PER_FRAME 20U
#define RADAR_CONFIG_CONFIDENCE_LOSS_PER_MISS 20U
#define RADAR_CONFIG_TRACK_CONFIDENCE_MIN 60U
#define RADAR_CONFIG_MAX_VELOCITY_MM_S 3000U
#define RADAR_CONFIG_EMA_ALPHA_PERCENT 60U
#define RADAR_CONFIG_MOTION_ENTER_FRAMES 3U
#define RADAR_CONFIG_MOTION_EXIT_FRAMES 8U
#define RADAR_CONFIG_TARGET_JUMP_MAX_MM 1500U

/* --------------------------- Person continuity -------------------------- */

/* These parameters only govern short-term business continuity.  They do not
 * turn a LD2450 slot or a motion track into a persistent human identity. */
#define RADAR_CONFIG_PERSON_STILL_HOLD_MS 3000U
#define RADAR_CONFIG_PERSON_DORMANT_TIMEOUT_MS 12000U
#define RADAR_CONFIG_PERSON_REACQUIRE_GATE_MM 2000U
#define RADAR_CONFIG_PERSON_SAME_ZONE_BONUS_MM 250U
#define RADAR_CONFIG_PERSON_ADJACENT_ZONE_ALLOW 1
#define RADAR_CONFIG_PERSON_NEW_CONFIRM_FRAMES 2U
#define RADAR_CONFIG_PERSON_NEW_NEAR_DORMANT_CONFIRM_FRAMES 3U
/* Keep short prediction bounded: velocity starts to decay after 400 ms and
 * reaches zero after another 600 ms. */
#define RADAR_CONFIG_PERSON_VELOCITY_DECAY_START_MS 400U
#define RADAR_CONFIG_PERSON_VELOCITY_DECAY_MS 600U

/* --------------------------- S3 任务与诊断 --------------------------- */

#define RADAR_CONFIG_LOCAL_ADAPTER_POLL_MS 20U
#define RADAR_CONFIG_LOCAL_ADAPTER_TASK_STACK 8192U
#define RADAR_CONFIG_LOCAL_ADAPTER_TASK_PRIORITY 3U
#define RADAR_CONFIG_DIAGNOSTICS_TASK_STACK 6144U
#define RADAR_CONFIG_DIAGNOSTICS_TASK_PRIORITY 2U
#define RADAR_CONFIG_DIAGNOSTICS_POLL_MS 250U
#define RADAR_CONFIG_DIAGNOSTICS_LOG_MS 500U
#define RADAR_CONFIG_LOG_TASK_STACK 6144U
#define RADAR_CONFIG_LOG_TASK_PRIORITY 1U

#endif
